<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\GeneralSetting;
use App\Http\Controllers\Controller;
use Excel;

class SettingController extends Controller
{
	public function index()
	{
		$settings = GeneralSetting::first();
		return view('admin.settings.index', ['page_title'=> 'Settings', 'general_settings' => $settings]);
	}

	public function saveGeneralSettings(Request $request){
		try {
			$settings = GeneralSetting::first();
			$settings->update($request->all());

			$result = ['success', 'Settings has been saved successfully', 'Success'];
		} catch (Exception $e) {
			$result = ['error', $e->getMessage(), 'Error'];
		}

		return redirect('settings#general_settings')->with('message', $result);
	}

	public function excelTojson(Request $request){

		Excel::load(storage_path() . '/app/public/translations2.xlsx', function($reader){

		    // Getting all results
		    $arr = array();
		    $reader->each(function($sheet) use($arr){

		$day = (60*60*24*(365));

		dd(($d1 - $bdate) / $day);

		$curl = curl_init();

		$datastring = json_encode([
			"apiOperation" => "CREATE_CHECKOUT_SESSION",
			"merchant" => "NRSINFOWAYSL",
			"order.id" => "1001",
			"order" => [
				"order.amount" => 100.00,
				"order.currency" => "AED",
			],
			"interaction" => [
				"interaction.operation" => "PURCHASE"
			]
		]);

        curl_setopt_array($curl, array(
            CURLOPT_URL => 'https://test-rakbankpay.mtf.gateway.mastercard.com/api/nvp/version/54',
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_ENCODING => "",
            CURLOPT_MAXREDIRS => 10,
            CURLOPT_TIMEOUT => 30,
            CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
            CURLOPT_CUSTOMREQUEST => "POST",
            CURLOPT_POSTFIELDS => $datastring,
            CURLOPT_HTTPHEADER => array(
                "content-type: application/json",
                "apiPassword: 294ddd6f4c0ebe800b899ee346f8a1b8",
				"apiUsername: merchant.NRSINFOWAYSL",
            ),
        ));

        $response = curl_exec($curl);
        $err = curl_error($curl);

        var_dump($response);

        curl_close($curl);

        // if ($err) {

        //     return false;

        // } else {

        //     $arr = json_decode($response);

        //     if(!empty($arr)){

        //         return $arr->access_token; 
        //     }

        //     return false;
        // }
		// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
		// $ch = curl_init();

		// curl_setopt_array($ch, array(
		//     CURLOPT_URL => 'https://test-rakbankpay.mtf.gateway.mastercard.com/api/nvp/version/54',
		//     CURLOPT_RETURNTRANSFER => true,
		//     CURLOPT_ENCODING => "",
		//     CURLOPT_MAXREDIRS => 10,
		//     CURLOPT_TIMEOUT => 30,
		//     CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
		//     CURLOPT_CUSTOMREQUEST => "POST",
		//     CURLOPT_POSTFIELDS => "{\"apiOperation\":\"CREATE_CHECKOUT_SESSION\",\"apiPassword\":\"aabf38b7ab511335ba2fb786206b1dc0\",\"interaction.returnUrl\":\"http::raktda.test/settings/excel\",\"apiUsername\":\"NRSINFOWAYSL\",\"merchant\":\"NRSINFOWAYSL\",\"order.id\":\"34234563\",\"order.amount\":\"100\",\"order.currency\":\"AED\"}",
		//     CURLOPT_HTTPHEADER => array(
		//         "content-type: application/json"
		//     ),
		// ));

		// $result = curl_exec($ch);
		// var_dump($result);


		// if (curl_errno($ch)) {
		//     echo 'Error:' . curl_error($ch);
		// }
		// curl_close($ch);

        // curl_close($curl);

        // if ($err) {
        //     return false;
        // } else {
        //     echo json_decode($response);
        // }

		//return view('admin.settings.checkout');
		// Excel::load(storage_path() . '/app/public/translations2.xlsx', function($reader){
		//     // Getting all results
		//     $arr = array();
		//     $reader->each(function($sheet) use($arr){

		//     	$key = $sheet['english'];
		//     	$value = $sheet['arabic'];

		//     	if($value != ''){
		//     		echo '"'.$key . '":"' . $value . '",<br>';
		//     	}

		    	
		    	
		//     	// dd($sheet['english']);
		// 	    // // // Loop through all rows
		// 	    // // $sheet->each(function($row) {

		// 	    // // 	dd($row->arabic);
		// 	    // // });
		// 	});
		    
			

		// });

		
	}
}
